# Generated by Django 5.0.1 on 2024-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField(default='Unknown Brand')),
                ('budget_range', models.IntegerField(default=0)),
                ('priority_user', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
