# Generated by Django 5.0.1 on 2024-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='priority_user',
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='name_phone',
            field=models.TextField(default='Unknown Brand'),
        ),
    ]
