# Generated by Django 5.0.1 on 2024-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbud', '0002_remove_mobilephone_priority_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobilePhone',
            new_name='Mobile',
        ),
    ]
