# Generated by Django 5.0.1 on 2024-02-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbud', '0003_rename_mobilephone_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='budget_range',
            field=models.TextField(default='Unknown'),
        ),
    ]
